server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rashmiranjan-Mishra/Hotel-Rating-System_ConfigServer
          clone-on-start: true
